import { useState, type FormEvent } from 'react';
import type { AuthSession } from '../services/AuthApi';
import { AuthApi } from '../services/AuthApi';

type Mode = 'login' | 'register' | 'recover';
const auth = new AuthApi();

export function AuthScreen({ onAuthenticated }: { onAuthenticated: (session: AuthSession) => void }) {
  const [mode, setMode] = useState<Mode>('login');
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [recoveryCode, setRecoveryCode] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [created, setCreated] = useState<(AuthSession & { recoveryCode: string }) | null>(null);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); setBusy(true); try { if (mode === 'register') setCreated(await auth.register({ name, email, password })); else if (mode === 'recover') onAuthenticated(await auth.resetPassword({ email, recoveryCode, password })); else onAuthenticated(await auth.login({ email, password })); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Hesap işlemi tamamlanamadı.'); } finally { setBusy(false); } };
  const changeMode = (next: Mode) => { setMode(next); setError(''); setPassword(''); setRecoveryCode(''); };
  const title = mode === 'login' ? 'Tekrar hoş geldin' : mode === 'register' ? 'Nova hesabını oluştur' : 'Şifreni yenile';
  const subtitle = mode === 'login' ? 'Sohbetlerine kaldığın yerden devam et.' : mode === 'register' ? 'Sohbet alanın birkaç saniyede hazır.' : 'Kayıt sırasında aldığın kurtarma kodunu kullan.';
  if (created) return <RecoveryCodeDialog code={created.recoveryCode} onClose={() => onAuthenticated(created)} />;
  return <main className="auth-page"><section className="auth-art" aria-hidden="true"><div className="auth-glow glow-one" /><div className="auth-glow glow-two" /><div className="auth-brand"><img className="auth-logo" src="/nova.svg" alt="" /><span>NOVA AI</span></div><div className="auth-copy"><p className="eyebrow">DÜŞÜN · ÜRET · KEŞFET</p><h1>Fikirlerin için sakin bir alan.</h1><p>Yaz, sor, tasarla. Nova AI, günün akışına uyum sağlayan sohbet alanın.</p></div><div className="auth-note">Gizliliğin önceliğimizdir. API anahtarların cihazına gönderilmez.</div></section><section className="auth-panel"><div className="auth-mobile-brand"><img className="auth-logo" src="/nova.svg" alt="" /> NOVA AI</div><div className="auth-card"><div className="auth-heading"><p className="eyebrow">NOVA HESAP</p><h2>{title}</h2><p>{subtitle}</p></div><form onSubmit={submit} className="auth-form">{mode === 'register' && <label>Adın<input autoComplete="name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Adın soyadın" required minLength={2} maxLength={60} /></label>}<label>E-posta<input autoComplete="email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="ornek@email.com" required /></label>{mode === 'recover' && <label>Kurtarma kodu<input autoComplete="one-time-code" value={recoveryCode} onChange={(event) => setRecoveryCode(event.target.value.toUpperCase())} placeholder="NOVA-ABC123..." required /></label>}<label>{mode === 'recover' ? 'Yeni şifre' : 'Şifre'}<input autoComplete={mode === 'login' ? 'current-password' : 'new-password'} type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="En az 10 karakter" required minLength={mode === 'login' ? 1 : 10} maxLength={128} /></label>{error && <p className="auth-error" role="alert">{error}</p>}<button className="auth-submit" disabled={busy}>{busy ? 'İşleniyor…' : mode === 'login' ? 'Giriş yap' : mode === 'register' ? 'Hesap oluştur' : 'Şifreyi yenile'} <span>→</span></button></form>{mode === 'login' && <button className="auth-text-button" onClick={() => changeMode('recover')}>Şifremi unuttum</button>}<p className="auth-switch">{mode === 'login' ? 'Henüz hesabın yok mu?' : 'Zaten hesabın var mı?'} <button onClick={() => changeMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'Kayıt ol' : 'Giriş yap'}</button></p></div></section></main>;
}

export function RecoveryCodeDialog({ code, onClose }: { code: string; onClose: () => void }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => { await navigator.clipboard?.writeText(code); setCopied(true); };
  return <div className="modal-backdrop recovery-backdrop"><section className="recovery-card" role="dialog" aria-modal="true" aria-labelledby="recovery-title"><img className="recovery-logo" src="/nova.svg" alt="Nova AI" /><p className="eyebrow">HESABIN HAZIR</p><h2 id="recovery-title">Kurtarma kodunu sakla</h2><p>Bu kod yalnızca şimdi gösterilir. Şifreni unutursan hesabına bununla erişebilirsin.</p><div className="recovery-code">{code}</div><button className="recovery-copy" onClick={copy}>{copied ? 'Kopyalandı' : 'Kodu kopyala'}</button><button className="auth-submit" onClick={onClose}>Sohbete devam et <span>→</span></button></section></div>;
}
