import type { Chat } from '../types/chat';
import { Icon } from './Icon';
type Props = { chats: Chat[]; activeId: string | null; open: boolean; query: string; setQuery: (text: string) => void; onNew: () => void; onSelect: (id: string) => void; onRename: (chat: Chat) => void; onDelete: (chat: Chat) => void; onExplore: () => void; onProfile: () => void; onSettings: () => void; onMemory: () => void; onClose: () => void; name: string; memoryCount: number };
export function ModernSidebar(props: Props) {
  const filtered = props.chats.filter(chat => `${chat.title} ${chat.messages.map(m => m.content).join(' ')}`.toLocaleLowerCase('tr-TR').includes(props.query.toLocaleLowerCase('tr-TR')));
  return <><button className={`scrim ${props.open ? 'visible' : ''}`} onClick={props.onClose} aria-label="Menüyü kapat" /><aside className={`sidebar ${props.open ? 'open' : ''}`}>
    <div className="side-head"><button className="brand" onClick={props.onNew}><span className="nova-symbol"><Icon name="spark" /></span><span>nova<span className="brand-ai"> ai</span></span></button><button className="mobile-close" onClick={props.onClose} aria-label="Menüyü kapat">×</button></div>
    <nav className="sidebar-nav" aria-label="Ana menü"><button className="nav-item" onClick={props.onNew}><Icon name="new" />Yeni sohbet<span className="shortcut">＋</span></button><label className="search"><Icon name="search" /><input value={props.query} onChange={e => props.setQuery(e.target.value)} placeholder="Sohbetlerde ara" aria-label="Sohbetlerde ara" /></label><button className="nav-item" onClick={props.onExplore}><Icon name="users" />Keşfet</button><button className="nav-item" onClick={props.onMemory}><Icon name="memory" />Bellek<span className="nav-count">{props.memoryCount}</span></button></nav>
    <div className="chat-list"><p>SOHBETLERİN</p>{filtered.length ? filtered.map(chat => <div className={`chat-row ${chat.id === props.activeId ? 'active' : ''}`} key={chat.id}><button className="chat-select" onClick={() => { props.onSelect(chat.id); props.onClose(); }}>{chat.title}</button><details><summary aria-label={`${chat.title} seçenekleri`}>···</summary><div className="menu"><button onClick={() => props.onRename(chat)}>Yeniden adlandır</button><button className="danger" onClick={() => props.onDelete(chat)}>Sil</button></div></details></div>) : <div className="empty-history">{props.query ? 'Eşleşen sohbet yok.' : 'Yeni fikirler, yeni sohbetler.\nGeçmişin burada görünecek.'}</div>}</div>
    <div className="sidebar-bottom"><button className="profile-shortcut" onClick={props.onProfile}><span className="profile-initial">{props.name.charAt(0).toLocaleUpperCase('tr-TR')}</span><span><strong>{props.name}</strong><small>Kişisel alanın</small></span></button><button className="sidebar-settings" onClick={props.onSettings} aria-label="Ayarlar"><Icon name="settings" /></button></div>
  </aside></>;
}
